name: Publish to npm

on:
  release:
    types: [published]

jobs:
  publish_npm:
    name: Publish to npm
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Node
        uses: actions/setup-node@v5
        with:
          cache: yarn
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: yarn install

      - name: Publish package
        run: yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
